/**
 * ScholarHub Static Scholarship Database
 * High-precision static directory of official state, national, and CSR scholarships.
 * Each scholarship contains criteria against which student profile attributes are evaluated.
 */

export const SCHOLARSHIPS_DATABASE = [
  // 1. MahaDBT Official Portal Schemes (mahadbt.maharashtra.gov.in)
  {
    id: "mahadbt-10th-1",
    name: "MahaDBT Rajarshi Chhatrapati Shahu Maharaj Merit Scholarship for 10th Passed Students",
    provider: "Social Justice Department — MahaDBT Portal",
    amount: 12000,
    amountFormatted: "₹12,000 / yr",
    deadline: "20 Nov 2026",
    daysLeft: 91,
    category: "Government",
    degree: "School",
    isGovt: true,
    portalUrl: "https://mahadbt.maharashtra.gov.in",
    criteria: {
      minTenthPercentage: 75,
      minPercentage: 75,
      maxIncome: 800000,
      allowedCategories: ["SC", "EBC", "General", "OBC"],
      allowedStreams: ["All"],
      allowedDegrees: ["School", "Higher Secondary (10+2)"],
      allowedStates: ["Maharashtra"],
      gender: "All",
    },
    description: "Special merit scholarship for 10th Board passed SC, OBC & EBC students taking admission in 11th & 12th Class junior colleges.",
    requirements: "Scored minimum 75% marks in Class 10th Board exam. Domicile of Maharashtra.",
  },
  {
    id: "mahadbt-1",
    name: "Rajarshi Chhatrapati Shahu Maharaj Shikshan Shulkh Shishyavrutti Yojna (MahaDBT EBC)",
    provider: "Government of Maharashtra (MahaDBT Portal)",
    amount: 60000,
    amountFormatted: "₹60,000 / yr",
    deadline: "15 Dec 2026",
    daysLeft: 116,
    category: "Engineering",
    degree: "Undergraduate",
    isGovt: true,
    portalUrl: "https://mahadbt.maharashtra.gov.in",
    criteria: {
      minPercentage: 60,
      maxIncome: 800000,
      allowedCategories: ["General", "EBC", "OBC", "EWS"],
      allowedStreams: ["Engineering", "Technology", "Degree", "B.Tech", "B.Sc", "Diploma"],
      allowedDegrees: ["Undergraduate", "Diploma"],
      allowedStates: ["Maharashtra"],
      gender: "All",
    },
    description: "50% to 100% tuition and exam fee reimbursement for EBC, OBC & General category students in engineering, degree & diploma courses.",
    requirements: "Domicile of Maharashtra. Annual family income below ₹8 Lakhs.",
  },
  {
    id: "mahadbt-2",
    name: "Dr. Punjabrao Deshmukh Vasatigruh Nirvah Bhatta Yojna (MahaDBT Hostel Allowance)",
    provider: "Government of Maharashtra (MahaDBT Portal)",
    amount: 30000,
    amountFormatted: "₹30,000 / yr",
    deadline: "31 Dec 2026",
    daysLeft: 132,
    category: "Engineering",
    degree: "Undergraduate",
    isGovt: true,
    portalUrl: "https://mahadbt.maharashtra.gov.in",
    criteria: {
      minPercentage: 60,
      maxIncome: 800000,
      requiresHostel: true,
      allowedLivingTypes: ["Hostel", "PG / Rented Accommodation"],
      allowedCategories: ["All"],
      allowedStreams: ["All"],
      allowedDegrees: ["Undergraduate", "Diploma"],
      allowedStates: ["Maharashtra"],
      gender: "All",
    },
    description: "Hostel maintenance allowance for children of small landholders and registered laborers studying in professional colleges.",
    requirements: "Hostel resident in Maharashtra. Domicile of Maharashtra State.",
  },
  {
    id: "mahadbt-obc-postmatric",
    name: "Post-Matric Tuition Fee and Examination Fee (Freeship) for OBC / SBC / VJNT Students",
    provider: "OBC & Bahujan Welfare Department (MahaDBT Portal)",
    amount: 48000,
    amountFormatted: "₹48,000 / yr",
    deadline: "30 Nov 2026",
    daysLeft: 101,
    category: "Government",
    degree: "Undergraduate",
    isGovt: true,
    portalUrl: "https://mahadbt.maharashtra.gov.in",
    criteria: {
      minPercentage: 50,
      maxIncome: 800000,
      allowedCategories: ["OBC", "SBC", "VJNT"],
      allowedStreams: ["All", "Engineering", "Arts", "Science", "Commerce"],
      allowedDegrees: ["Undergraduate", "Postgraduate", "Diploma"],
      allowedStates: ["Maharashtra"],
      gender: "All",
    },
    description: "Full tuition and examination fee assistance for backward class students enrolled in approved colleges in Maharashtra.",
    requirements: "Valid OBC/VJNT/SBC caste certificate & non-creamy layer. Annual family income <= ₹8 Lakhs.",
  },
  {
    id: "mahadbt-10th-2",
    name: "MahaDBT Post-Matric Scholarship for 10th/12th Class Students (OBC/VJNT/SBC)",
    provider: "VJNT, OBC & SBC Welfare Dept — MahaDBT Portal",
    amount: 15000,
    amountFormatted: "₹15,000 / yr",
    deadline: "05 Dec 2026",
    daysLeft: 106,
    category: "Government",
    degree: "School",
    isGovt: true,
    portalUrl: "https://mahadbt.maharashtra.gov.in",
    criteria: {
      minPercentage: 50,
      maxIncome: 150000,
      allowedCategories: ["OBC", "VJNT", "SBC"],
      allowedStreams: ["All"],
      allowedDegrees: ["School", "Higher Secondary (10+2)"],
      allowedStates: ["Maharashtra"],
      gender: "All",
    },
    description: "Tuition fee and exam fee financial assistance for 10th board passed students enrolled in Class 11th and 12th stream.",
    requirements: "Enrolled in 11th or 12th Class. Annual family income below ₹1.5 Lakhs.",
  },
  {
    id: "mahajyoti-10th",
    name: "MahaJYOTI MHT-CET/JEE/NEET Free Coaching & Tab Allowance for 10th Passed Students",
    provider: "MahaJYOTI Govt of Maharashtra (mahajyoti.org.in)",
    amount: 25000,
    amountFormatted: "₹25,000 + Free Tab",
    deadline: "15 Dec 2026",
    daysLeft: 116,
    category: "Government",
    degree: "School",
    isGovt: true,
    portalUrl: "https://mahajyoti.org.in",
    criteria: {
      minTenthPercentage: 70,
      minPercentage: 70,
      maxIncome: 800000,
      allowedCategories: ["OBC", "VJNT", "SBC"],
      allowedStreams: ["All", "STEM", "Science"],
      allowedDegrees: ["School", "Higher Secondary (10+2)"],
      allowedStates: ["Maharashtra"],
      gender: "All",
    },
    description: "Free 11th & 12th Class entrance coaching (JEE/NEET/CET) plus free Android tablet for OBC/VJNT/SBC students.",
    requirements: "Passed 10th Board Exam with 70%+ marks. Domicile of Maharashtra.",
  },
  {
    id: "vidya-10th",
    name: "Vidyasaarathi Post-10th & 12th Standard Merit Scholarship",
    provider: "NSDL Vidyasaarathi Corporate CSR",
    amount: 20000,
    amountFormatted: "₹20,000 / yr",
    deadline: "10 Nov 2026",
    daysLeft: 81,
    category: "General",
    degree: "School",
    isGovt: false,
    portalUrl: "https://www.vidyasaarathi.co.in",
    criteria: {
      minTenthPercentage: 60,
      minPercentage: 60,
      maxIncome: 350000,
      allowedCategories: ["All"],
      allowedStreams: ["All"],
      allowedDegrees: ["School", "Higher Secondary (10+2)", "Diploma"],
      allowedStates: ["All India", "Maharashtra"],
      gender: "All",
    },
    description: "CSR financial grant for meritorious students pursuing 11th, 12th, or ITI diploma courses after 10th Class.",
    requirements: "Enrolled in 11th, 12th or ITI. Family income below ₹3.5 Lakhs.",
  },
  {
    id: "nmmss-10th",
    name: "National Means-cum-Merit Scholarship Scheme (NMMSS Class 10th-12th)",
    provider: "Ministry of Education (Govt of India) — NSP",
    amount: 12000,
    amountFormatted: "₹12,000 / yr",
    deadline: "30 Nov 2026",
    daysLeft: 101,
    category: "Government",
    degree: "School",
    isGovt: true,
    portalUrl: "https://scholarships.gov.in",
    criteria: {
      minTenthPercentage: 55,
      minPercentage: 55,
      maxIncome: 350000,
      allowedCategories: ["All"],
      allowedStreams: ["All"],
      allowedDegrees: ["School", "Higher Secondary (10+2)"],
      allowedStates: ["All India", "Maharashtra"],
      gender: "All",
    },
    description: "Central government scholarship grant for meritorious school students studying in Class 10th, 11th, and 12th.",
    requirements: "Scored 55% in 8th/9th/10th class. Annual family income below ₹3.5 Lakhs.",
  },
  {
    id: "mahadbt-4",
    name: "Government Post-Matric Scholarship for SC & ST Students (MahaDBT)",
    provider: "Social Justice & Special Assistance Dept — MahaDBT",
    amount: 75000,
    amountFormatted: "₹75,000 / yr",
    deadline: "05 Jan 2027",
    daysLeft: 137,
    category: "Government",
    degree: "Undergraduate",
    isGovt: true,
    portalUrl: "https://mahadbt.maharashtra.gov.in",
    criteria: {
      minPercentage: 50,
      maxIncome: 250000,
      allowedCategories: ["SC", "ST"],
      allowedStreams: ["All"],
      allowedDegrees: ["Undergraduate", "Postgraduate", "Diploma"],
      allowedStates: ["Maharashtra"],
      gender: "All",
    },
    description: "Full course tuition fee reimbursement plus monthly maintenance allowance for SC/ST students in Maharashtra.",
    requirements: "SC / ST caste certificate. Domicile of Maharashtra.",
  },

  // 2. MahaJYOTI Official Portal Schemes (mahajyoti.org.in)
  {
    id: "mahajyoti-1",
    name: "MahaJYOTI MPhil & PhD Research Fellowship Scheme",
    provider: "MahaJYOTI Govt of Maharashtra (mahajyoti.org.in)",
    amount: 372000,
    amountFormatted: "₹31,000 / mo",
    deadline: "31 Dec 2026",
    daysLeft: 132,
    category: "Research",
    degree: "Postgraduate",
    isGovt: true,
    portalUrl: "https://mahajyoti.org.in",
    criteria: {
      minPercentage: 65,
      maxIncome: 800000,
      allowedCategories: ["OBC", "VJNT", "SBC"],
      allowedStreams: ["STEM", "Science", "Arts", "Commerce", "Engineering"],
      allowedDegrees: ["Postgraduate", "Doctorate / PhD"],
      allowedStates: ["Maharashtra"],
      gender: "All",
    },
    description: "Monthly research fellowship stipend of ₹31,000 + HRA for OBC/VJNT/SBC scholars pursuing PhD & MPhil research degrees.",
    requirements: "OBC/VJNT/SBC category. Enrolled in recognized university PhD program.",
  },
  {
    id: "mahajyoti-upsc",
    name: "MahaJYOTI Competitive Examination Guidance & Monthly Stipend",
    provider: "MahaJYOTI (mahajyoti.org.in)",
    amount: 120000,
    amountFormatted: "₹10,000 / mo",
    deadline: "15 Jan 2027",
    daysLeft: 147,
    category: "Government",
    degree: "Undergraduate",
    isGovt: true,
    portalUrl: "https://mahajyoti.org.in",
    criteria: {
      minPercentage: 55,
      maxIncome: 800000,
      allowedCategories: ["OBC", "VJNT", "SBC"],
      allowedStreams: ["All"],
      allowedDegrees: ["Undergraduate", "Postgraduate"],
      allowedStates: ["Maharashtra"],
      gender: "All",
    },
    description: "Financial stipend of ₹10,000/month plus free coaching assistance for civil services & government examinations.",
    requirements: "Graduate or in final year of degree. Domicile of Maharashtra.",
  },

  // 3. Vidyasaarathi Corporate CSR Schemes (vidyasaarathi.co.in)
  {
    id: "vidya-1",
    name: "ACC Vidyasaarathi Scholarship for B.E / B.Tech Students",
    provider: "ACC Limited & NSDL Vidyasaarathi Portal",
    amount: 50000,
    amountFormatted: "₹50,000 / yr",
    deadline: "10 Nov 2026",
    daysLeft: 81,
    category: "Engineering",
    degree: "Undergraduate",
    isGovt: false,
    portalUrl: "https://www.vidyasaarathi.co.in",
    criteria: {
      minPercentage: 60,
      maxIncome: 500000,
      allowedCategories: ["All"],
      allowedStreams: ["Engineering", "Technology", "B.Tech", "B.E"],
      allowedDegrees: ["Undergraduate"],
      allowedStates: ["All India", "Maharashtra"],
      gender: "All",
    },
    description: "Corporate CSR scholarship for undergraduate engineering students admitted to accredited B.E / B.Tech programs.",
    requirements: "Minimum 60% in Class 12 / Diploma. Annual family income below ₹5 Lakhs.",
  },
  {
    id: "vidya-tata",
    name: "Tata Steel Millennium Scholarship for Professional Degree Students",
    provider: "Tata Steel CSR & Vidyasaarathi Portal",
    amount: 40000,
    amountFormatted: "₹40,000 / yr",
    deadline: "25 Nov 2026",
    daysLeft: 96,
    category: "Engineering",
    degree: "Undergraduate",
    isGovt: false,
    portalUrl: "https://www.vidyasaarathi.co.in",
    criteria: {
      minPercentage: 65,
      maxIncome: 600000,
      allowedCategories: ["All"],
      allowedStreams: ["Engineering", "Medical", "Architecture", "Technology"],
      allowedDegrees: ["Undergraduate"],
      allowedStates: ["All India", "Maharashtra"],
      gender: "All",
    },
    description: "Prestigious corporate merit scholarship for meritorious students enrolled in 4-year professional graduation programs.",
    requirements: "Passed 10+2 with >= 65% marks. Full-time enrolled candidate.",
  },

  // 4. Central Government NSP Schemes
  {
    id: "nsp-1",
    name: "Central Sector Scheme of Scholarships for College & University Students (CSSS)",
    provider: "Ministry of Education (Govt of India) — NSP",
    amount: 20000,
    amountFormatted: "₹20,000 / yr",
    deadline: "31 Oct 2026",
    daysLeft: 71,
    category: "Government",
    degree: "Undergraduate",
    isGovt: true,
    portalUrl: "https://scholarships.gov.in",
    criteria: {
      minPercentage: 80,
      maxIncome: 450000,
      allowedCategories: ["All"],
      allowedStreams: ["All"],
      allowedDegrees: ["Undergraduate", "Postgraduate"],
      allowedStates: ["All India", "Maharashtra"],
      gender: "All",
    },
    description: "Financial assistance for meritorious students from low-income families pursuing regular graduate and post-graduate courses.",
    requirements: "Above 80th percentile in Class 12 board exam. Annual family income below ₹4.5 Lakhs.",
  },
  {
    id: "aicte-pragati",
    name: "AICTE Pragati Scholarship Scheme for Girl Students (Technical Degree / Diploma)",
    provider: "All India Council for Technical Education (AICTE)",
    amount: 50000,
    amountFormatted: "₹50,000 / yr",
    deadline: "30 Nov 2026",
    daysLeft: 101,
    category: "Engineering",
    degree: "Undergraduate",
    isGovt: true,
    portalUrl: "https://www.aicte-india.org",
    criteria: {
      minPercentage: 60,
      maxIncome: 800000,
      allowedCategories: ["All"],
      allowedStreams: ["Engineering", "Technology", "Diploma", "B.Tech"],
      allowedDegrees: ["Undergraduate", "Diploma"],
      allowedStates: ["All India", "Maharashtra"],
      gender: "Female",
    },
    description: "Empowering female candidates pursuing technical degree and diploma courses in AICTE approved institutions across India.",
    requirements: "Female candidate admitted to 1st year degree/diploma program. Family income <= ₹8 Lakhs.",
  },
  {
    id: "reliance-foundation",
    name: "Reliance Foundation Undergraduate Scholarship in STEM & Liberal Arts",
    provider: "Reliance Foundation (CSR Initiative)",
    amount: 200000,
    amountFormatted: "₹2,00,000 Total",
    deadline: "15 Dec 2026",
    daysLeft: 116,
    category: "Engineering",
    degree: "Undergraduate",
    isGovt: false,
    portalUrl: "https://www.reliancefoundation.org",
    criteria: {
      minPercentage: 60,
      maxIncome: 1500000,
      allowedCategories: ["All"],
      allowedStreams: ["Engineering", "Science", "Commerce", "Arts", "Technology"],
      allowedDegrees: ["Undergraduate"],
      allowedStates: ["All India", "Maharashtra"],
      gender: "All",
    },
    description: "Up to ₹2,00,000 financial support over the duration of degree for visionary first-year undergraduate students.",
    requirements: "Passed Class 12 with minimum 60% marks. Enrolled in 1st year regular degree.",
  },
  {
    id: "inspire-dst",
    name: "INSPIRE Scholarship for Higher Education (SHE) in Natural & Basic Sciences",
    provider: "Department of Science & Technology (DST Govt of India)",
    amount: 80000,
    amountFormatted: "₹80,000 / yr",
    deadline: "31 Dec 2026",
    daysLeft: 132,
    category: "Research",
    degree: "Undergraduate",
    isGovt: true,
    portalUrl: "https://online-inspire.gov.in",
    criteria: {
      minPercentage: 85,
      maxIncome: 1200000,
      allowedCategories: ["All"],
      allowedStreams: ["Science", "STEM", "Physics", "Chemistry", "Mathematics", "Biology"],
      allowedDegrees: ["Undergraduate", "Postgraduate"],
      allowedStates: ["All India", "Maharashtra"],
      gender: "All",
    },
    description: "Scholarship of ₹80,000/year (₹60,000 stipend + ₹20,000 summer project mentorship) for top 1% meritorious science students.",
    requirements: "Top 1% rank in Class 12 board examination. Enrolled in B.Sc, B.S., or Int. M.Sc.",
  },
];
