/**
 * ScholarHub Global Scholarship Database
 * Each scholarship contains explicit eligibility criteria against which
 * student profile attributes are evaluated.
 */

export const SCHOLARSHIPS_DATABASE = [
  {
    id: "s1",
    name: "National Merit STEM Grant",
    provider: "National Science Foundation",
    amount: 50000,
    amountFormatted: "₹50,000",
    deadline: "18 Aug 2026",
    daysLeft: 12,
    category: "STEM",
    degree: "Undergraduate",
    criteria: {
      minPercentage: 75,
      maxIncome: 600000,
      allowedCategories: ["All"],
      allowedStreams: ["STEM", "Science", "Engineering", "Technology", "Computer Science", "B.Tech", "B.Sc", "BCA", "Information Technology"],
      allowedDegrees: ["Undergraduate", "Postgraduate"],
      allowedStates: ["All India"],
      gender: "All",
    },
    description: "Financial grant for undergraduate students pursuing Science, Technology, and Mathematics degrees.",
    requirements: "Minimum 75% aggregate score in 12th/previous semester. Annual family income below ₹6 Lakhs.",
  },
  {
    id: "s2",
    name: "State Girls in Tech Fund",
    provider: "State Education Council",
    amount: 35000,
    amountFormatted: "₹35,000",
    deadline: "12 Sep 2026",
    daysLeft: 37,
    category: "Technology",
    degree: "Undergraduate",
    criteria: {
      minPercentage: 70,
      maxIncome: 800000,
      allowedCategories: ["All"],
      allowedStreams: ["Computer Science", "IT", "Information Technology", "AI", "Artificial Intelligence", "Technology", "Engineering", "B.Tech", "BCA", "MCA", "Data Science"],
      allowedDegrees: ["Undergraduate", "Postgraduate"],
      allowedStates: ["All India"],
      gender: "Female",
    },
    description: "Empowering female students enrolled in Computer Science, IT, and Artificial Intelligence programs.",
    requirements: "Enrolled in accredited IT/CS course. Open to female candidates across all states with min 70% marks.",
  },
  {
    id: "s3",
    name: "First-Gen Excellence Award",
    provider: "Global Higher Ed Trust",
    amount: 40000,
    amountFormatted: "₹40,000",
    deadline: "30 Sep 2026",
    daysLeft: 55,
    category: "General",
    degree: "Undergraduate",
    criteria: {
      minPercentage: 65,
      maxIncome: 450000,
      allowedCategories: ["All"],
      allowedStreams: ["All"],
      allowedDegrees: ["Undergraduate", "Higher Secondary (10+2)", "Postgraduate"],
      allowedStates: ["All India"],
      gender: "All",
      specialCriteriaRequired: "First-Generation Learner",
    },
    description: "Dedicated scholarship award for first-generation university students with demonstrated merit.",
    requirements: "First person in immediate family to pursue higher university education. Income under ₹4.5 Lakhs.",
  },
  {
    id: "s4",
    name: "Global Engineering Fellowship",
    provider: "International Tech Alliance",
    amount: 75000,
    amountFormatted: "₹75,000",
    deadline: "15 Oct 2026",
    daysLeft: 70,
    category: "Engineering",
    degree: "Postgraduate",
    criteria: {
      minPercentage: 80,
      maxIncome: 800000,
      allowedCategories: ["All"],
      allowedStreams: ["Engineering", "Technology", "Computer Science", "Robotics", "AI", "Mechanical", "Electrical", "Civil", "B.Tech", "M.Tech"],
      allowedDegrees: ["Undergraduate", "Postgraduate"],
      allowedStates: ["All India"],
      gender: "All",
    },
    description: "Prestige scholarship for outstanding engineering undergraduates and postgraduates specializing in advanced technologies.",
    requirements: "Minimum 80% mark / 8.0 CGPA in previous semester. Engineering degree curriculum.",
  },
  {
    id: "s5",
    name: "Higher Education Merit Scholarship",
    provider: "Ministry of Education",
    amount: 60000,
    amountFormatted: "₹60,000",
    deadline: "01 Nov 2026",
    daysLeft: 87,
    category: "Merit",
    degree: "Undergraduate",
    criteria: {
      minPercentage: 85,
      maxIncome: 500000,
      allowedCategories: ["All"],
      allowedStreams: ["All"],
      allowedDegrees: ["Undergraduate", "Postgraduate"],
      allowedStates: ["All India"],
      gender: "All",
    },
    description: "Merit-cum-means scholarship for post-secondary education across recognized institutions.",
    requirements: "Demonstrated academic excellence (85%+ score) and family income below ₹5 Lakhs.",
  },
  {
    id: "s6",
    name: "AI & Machine Learning Research Grant",
    provider: "Advanced AI Research Institute",
    amount: 90000,
    amountFormatted: "₹90,000",
    deadline: "10 Nov 2026",
    daysLeft: 96,
    category: "Technology",
    degree: "Postgraduate",
    criteria: {
      minPercentage: 80,
      maxIncome: 1000000,
      allowedCategories: ["All"],
      allowedStreams: ["Computer Science", "Artificial Intelligence", "Data Science", "Machine Learning", "Technology", "B.Tech", "M.Tech", "PhD"],
      allowedDegrees: ["Postgraduate", "Doctorate / PhD", "Undergraduate"],
      allowedStates: ["All India"],
      gender: "All",
    },
    description: "Research funding for students conducting projects in Deep Learning, Computer Vision, or NLP.",
    requirements: "Enrolled in AI/ML or CS advanced curriculum with 80%+ previous score.",
  },
  {
    id: "s7",
    name: "Maharashtra State Post-Matric OBC & SC/ST Scholarship",
    provider: "Department of Social Justice",
    amount: 45000,
    amountFormatted: "₹45,000",
    deadline: "20 Oct 2026",
    daysLeft: 75,
    category: "Merit",
    degree: "Undergraduate",
    criteria: {
      minPercentage: 60,
      maxIncome: 300000,
      allowedCategories: ["OBC", "SC", "ST", "EWS"],
      allowedStreams: ["All"],
      allowedDegrees: ["Undergraduate", "Postgraduate", "Higher Secondary (10+2)"],
      allowedStates: ["Maharashtra"],
      gender: "All",
    },
    description: "State government tuition & exam fee support for reserved category students domiciled in Maharashtra.",
    requirements: "OBC/SC/ST/EWS category, family income below ₹3 Lakhs, and Maharashtra domicile.",
  },
  {
    id: "s8",
    name: "Rural Student Empowerment Fund",
    provider: "Rural Advancement Foundation",
    amount: 30000,
    amountFormatted: "₹30,000",
    deadline: "25 Sep 2026",
    daysLeft: 50,
    category: "General",
    degree: "High School",
    criteria: {
      minPercentage: 60,
      maxIncome: 300000,
      allowedCategories: ["All"],
      allowedStreams: ["All"],
      allowedDegrees: ["Higher Secondary (10+2)", "Undergraduate"],
      allowedStates: ["All India"],
      gender: "All",
    },
    description: "Support for talented students from rural districts entering higher education.",
    requirements: "Family income under ₹3 Lakhs and minimum 60% marks in previous examination.",
  },
  {
    id: "s9",
    name: "Biomedical & Healthcare Innovation Scholarship",
    provider: "Healthcare Tech Foundation",
    amount: 80000,
    amountFormatted: "₹80,000",
    deadline: "05 Dec 2026",
    daysLeft: 121,
    category: "STEM",
    degree: "Postgraduate",
    criteria: {
      minPercentage: 75,
      maxIncome: 700000,
      allowedCategories: ["All"],
      allowedStreams: ["Biotechnology", "Pharmacy", "Bioengineering", "Medical", "MBBS", "B.Sc", "M.Sc", "STEM", "Science"],
      allowedDegrees: ["Undergraduate", "Postgraduate"],
      allowedStates: ["All India"],
      gender: "All",
    },
    description: "Funding for students pursuing degrees in Biotechnology, Pharmacy, or Bioengineering.",
    requirements: "Enrolled in Biomedical/Pharma/Life Sciences program with min 75% marks.",
  },
  {
    id: "s10",
    name: "National PwD Empowerment Education Grant",
    provider: "Empowerment of Persons with Disabilities Board",
    amount: 55000,
    amountFormatted: "₹55,000",
    deadline: "15 Dec 2026",
    daysLeft: 130,
    category: "Merit",
    degree: "Undergraduate",
    criteria: {
      minPercentage: 50,
      maxIncome: 600000,
      allowedCategories: ["All"],
      allowedStreams: ["All"],
      allowedDegrees: ["Undergraduate", "Postgraduate", "Higher Secondary (10+2)"],
      allowedStates: ["All India"],
      gender: "All",
      disabilityRequired: true,
    },
    description: "Financial assistance for students with disabilities pursuing graduate and technical degrees.",
    requirements: "PwD status (>=40% disability) and family income under ₹6 Lakhs.",
  },
];
