/**
 * ScholarHub Global Scholarship Database
 * Each scholarship contains explicit eligibility criteria against which
 * student profile attributes are evaluated.
 */

export const SCHOLARSHIPS_DATABASE = [
  // 1. MahaDBT Official Portal Schemes (mahadbt.maharashtra.gov.in)
  {
    id: "mahadbt-10th-1",
    name: "MahaDBT Rajarshi Chhatrapati Shahu Maharaj Merit Scholarship for 10th Passed Students",
    provider: "Social Justice Department — MahaDBT Portal",
    amount: 12000,
    amountFormatted: "₹12,000 / yr",
    deadline: "20 Nov 2026",
    daysLeft: 91,
    category: "Government",
    degree: "School",
    isGovt: true,
    portalUrl: "https://mahadbt.maharashtra.gov.in",
    criteria: {
      minPercentage: 75,
      maxIncome: 800000,
      allowedCategories: ["SC", "EBC", "General"],
      allowedStreams: ["All"],
      allowedDegrees: ["School", "Higher Secondary (10+2)"],
      allowedStates: ["Maharashtra"],
      gender: "All",
    },
    description: "Special merit scholarship for 10th Board passed SC & EBC students taking admission in 11th & 12th Class junior colleges.",
    requirements: "Scored minimum 75% marks in Class 10th Board exam. Domicile of Maharashtra.",
  },
  {
    id: "mahadbt-1",
    name: "Rajarshi Chhatrapati Shahu Maharaj Shikshan Shulkh Shishyavrutti Yojna (MahaDBT EBC)",
    provider: "Government of Maharashtra (MahaDBT Portal)",
    amount: 60000,
    amountFormatted: "₹60,000 / yr",
    deadline: "15 Dec 2026",
    daysLeft: 116,
    category: "Engineering",
    degree: "Undergraduate",
    isGovt: true,
    portalUrl: "https://mahadbt.maharashtra.gov.in",
    criteria: {
      minPercentage: 60,
      maxIncome: 800000,
      allowedCategories: ["General", "EBC"],
      allowedStreams: ["Engineering", "Technology", "Degree", "B.Tech", "B.Sc", "Diploma"],
      allowedDegrees: ["Undergraduate", "Diploma"],
      allowedStates: ["Maharashtra"],
      gender: "All",
    },
    description: "50% to 100% tuition and exam fee reimbursement for EBC & General category students in engineering, degree & diploma courses.",
    requirements: "Domicile of Maharashtra. Annual family income below ₹8 Lakhs.",
  },
  {
    id: "mahadbt-2",
    name: "Dr. Punjabrao Deshmukh Vasatigruh Nirvah Bhatta Yojna (MahaDBT Hostel Allowance)",
    provider: "Government of Maharashtra (MahaDBT Portal)",
    amount: 30000,
    amountFormatted: "₹30,000 / yr",
    deadline: "31 Dec 2026",
    daysLeft: 132,
    category: "Engineering",
    degree: "Undergraduate",
    isGovt: true,
    portalUrl: "https://mahadbt.maharashtra.gov.in",
    criteria: {
      minPercentage: 60,
      maxIncome: 800000,
      allowedCategories: ["All"],
      allowedStreams: ["All"],
      allowedDegrees: ["Undergraduate", "Diploma"],
      allowedStates: ["Maharashtra"],
      gender: "All",
    },
    description: "Hostel maintenance allowance for children of small landholders and registered laborers studying in professional colleges.",
    requirements: "Hostel resident in Maharashtra. Domicile of Maharashtra State.",
  },

  // 2. MahaJYOTI Official Portal Schemes (mahajyoti.org.in)
  {
    id: "mahajyoti-1",
    name: "MahaJYOTI MPhil & PhD Research Fellowship Scheme",
    provider: "MahaJYOTI Govt of Maharashtra (mahajyoti.org.in)",
    amount: 372000,
    amountFormatted: "₹31,000 / mo",
    deadline: "31 Dec 2026",
    daysLeft: 132,
    category: "Research",
    degree: "Postgraduate",
    isGovt: true,
    portalUrl: "https://mahajyoti.org.in",
    criteria: {
      minPercentage: 65,
      maxIncome: 800000,
      allowedCategories: ["OBC", "VJNT", "SBC"],
      allowedStreams: ["STEM", "Science", "Arts", "Commerce"],
      allowedDegrees: ["Postgraduate", "Doctorate / PhD"],
      allowedStates: ["Maharashtra"],
      gender: "All",
    },
    description: "Monthly research fellowship stipend of ₹31,000 + HRA for OBC/VJNT/SBC scholars pursuing PhD & MPhil research degrees.",
    requirements: "OBC/VJNT/SBC category. Enrolled in recognized university PhD program.",
  },

  // 3. Vidyasaarathi Corporate CSR Schemes (vidyasaarathi.co.in)
  {
    id: "vidya-1",
    name: "ACC Vidyasaarathi Scholarship for B.E / B.Tech Students",
    provider: "ACC Limited & NSDL Vidyasaarathi Portal",
    amount: 50000,
    amountFormatted: "₹50,000 / yr",
    deadline: "10 Nov 2026",
    daysLeft: 81,
    category: "Engineering",
    degree: "Undergraduate",
    isGovt: false,
    portalUrl: "https://www.vidyasaarathi.co.in",
    criteria: {
      minPercentage: 60,
      maxIncome: 500000,
      allowedCategories: ["All"],
      allowedStreams: ["Engineering", "Technology", "B.Tech", "B.E"],
      allowedDegrees: ["Undergraduate"],
      allowedStates: ["All India"],
      gender: "All",
    },
    description: "Corporate CSR scholarship for undergraduate engineering students admitted to accredited B.E / B.Tech programs.",
    requirements: "Minimum 60% in Class 12 / Diploma. Annual family income below ₹5 Lakhs.",
  },

  // 4. Central Government NSP Schemes
  {
    id: "nsp-1",
    name: "Central Sector Scheme of Scholarships for College & University Students (CSSS)",
    provider: "Ministry of Education (Govt of India) — NSP",
    amount: 20000,
    amountFormatted: "₹20,000 / yr",
    deadline: "31 Oct 2026",
    daysLeft: 71,
    category: "Government",
    degree: "Undergraduate",
    isGovt: true,
    portalUrl: "https://scholarships.gov.in",
    criteria: {
      minPercentage: 80,
      maxIncome: 450000,
      allowedCategories: ["All"],
      allowedStreams: ["All"],
      allowedDegrees: ["Undergraduate", "Postgraduate"],
      allowedStates: ["All India"],
      gender: "All",
    },
    description: "Financial assistance for meritorious students from low-income families pursuing regular graduate and post-graduate courses.",
    requirements: "Above 80th percentile in Class 12 board exam. Annual family income below ₹4.5 Lakhs.",
  }
];
